### ISSUE TITLE
With insecure ssl connections on python 3.6+: Max recursion error 

### ISSUE THREAD

**Issue by lee-pai-long** [lee-pai-long/boom#1]
```
Traceback (most recent call last):
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/lpl/projects/perso/boom/boom/boom.py", line 393, in onecall
    res = post_hook(method(url, **options))
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/urllib3/connection.py", line 314, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 269, in create_urllib3_context
    context.options |= options
  File "/home/lpl/.pyenv/versions/3.6.3/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/home/lpl/.pyenv/versions/3.6.3/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/home/lpl/.pyenv/versions/3.6.3/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 317 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/gevent/hub.py", line 846, in switch
    switch(value)
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/gevent/greenlet.py", line 536, in run
    self._report_error(sys.exc_info())
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/gevent/greenlet.py", line 518, in _report_error
    self._exc_info = exc_info[0], exc_info[1], dump_traceback(exc_info[2])
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/gevent/_tblib.py", line 243, in g
    return f(a)
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/gevent/_tblib.py", line 298, in dump_traceback
    return dumps(tb)
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/gevent/_tblib.py", line 217, in pickle_traceback
    return unpickle_traceback, (Frame(tb.tb_frame), tb.tb_lineno, tb.tb_next and Traceback(tb.tb_next))
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/gevent/_tblib.py", line 156, in __init__
    self.tb_next = Traceback(tb.tb_next)
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/gevent/_tblib.py", line 156, in __init__
    self.tb_next = Traceback(tb.tb_next)
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/gevent/_tblib.py", line 156, in __init__
    self.tb_next = Traceback(tb.tb_next)
  [Previous line repeated 238 more times]
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/gevent/_tblib.py", line 151, in __init__
    self.tb_frame = Frame(tb.tb_frame)
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/gevent/_tblib.py", line 146, in __init__
    self.f_code = Code(frame.f_code)
RecursionError: maximum recursion depth exceeded while calling a Python object
<built-in method switch of Greenlet object at 0x7ff6dc8d8898> failed with RecursionError

 Done
Traceback (most recent call last):
  File "/home/lpl/.pyenv/versions/badaboom/bin/boom", line 11, in <module>
    load_entry_point('boom', 'console_scripts', 'boom')()
  File "/home/lpl/projects/perso/boom/boom/boom.py", line 703, in main
    data_file=scenario.get('data_file', None)
  File "/home/lpl/projects/perso/boom/boom/boom.py", line 536, in load
    insecure=insecure
  File "/home/lpl/projects/perso/boom/boom/boom.py", line 446, in run
    pool.join()
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/gevent/pool.py", line 527, in join
    self._empty_event.wait(timeout=timeout)
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/gevent/event.py", line 207, in wait
    return self._wait(timeout)
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/gevent/event.py", line 117, in _wait
    gotit = self._wait_core(timeout)
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/gevent/event.py", line 95, in _wait_core
    result = self.hub.switch()
  File "/home/lpl/.pyenv/versions/3.6.3/envs/badaboom/lib/python3.6/site-packages/gevent/hub.py", line 609, in switch
    return greenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x7ff6dc8d8800 epoll default pending=0 ref=0 fileno=4 resolver=<gevent.resolver_thread.Resolver at 0x7ff6dc6828d0 pool=<ThreadPool at 0x7ff6dc682940 0/1/10>> threadpool=<ThreadPool at 0x7ff6dc682940 0/1/10>>)
```

**Comment by lee-pai-long** [comment]
Please follow progress at https://gitlab.com/lee-pai-long/boom/issues/1 since this copy of the project will not be maintained.
